server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Xử lý route client-side (React Router)
    location / {
        try_files $uri /index.html;
    }

    # Tuỳ chọn: Nếu bạn muốn proxy request API về backend trong cùng network Docker
    # location /api/ {
    #     proxy_pass http://backend:3000;
    # }
}
